oracle_user:                     "oracle"
root_user:                       "root"
oracle_install_group:            "oinstall"
root_directory:                  "/u01"
scripts_directory:               "{{ root_directory }}/app/scripts"
base_directory:                  "{{ root_directory }}/app/oracle"
oracle_home:                     "{{ base_directory }}/product/19.2.0/db100"
prihost:                         ora-x1 
prdbunq_name:                    eaymp  
sbhost:                          ora-x2 
sbdbunq_name:                    pmjks  
db_recofile_path:                USE_DB_RECOVERY_FILE_DEST
password_sys:                    "Oracle123"
db_createfile_path:              "/u01/app/oracle/oradata" 
oracle_prsid:                    eaymp
oracle_sbsid:                    pmjks
db_recofile_dest:                "/u01/app/oracle/redo" 
oratab:                          /etc/oratab
stage_dir:                       "/u01/stage"
log_dir:                         "/u01/stage/logs"
silent_listener_config_file:     "{{ stage_dir }}/silent-lsnr19c-config.rsp"
tns_path: "{{ oracle_home }}/network/admin"
tns_file: "{{ tns_path }}/tnsnames.ora"
stlsnr_file: "{{ tns_path }}/listener.ora"
lsnr_name: LISTENER
portnum: 1521
